### ISSUE TITLE
Bump JSHint to 2.8.0

### ISSUE THREAD

**Issue by choweiyuan** [webjars/jshint#13]
https://github.com/jshint/jshint/releases/tag/2.8.0

**Comment by choweiyuan** [comment]
Thanks.. one question..
why is it not on http://mvnrepository.com/artifact/org.webjars/jshint yet...?

**Comment by jamesward** [comment]
Whoops.  I forgot that this WebJar requires manual deployment.  I'm doing that now.  It should be there in a few hours.
