### ISSUE TITLE
Update to 2.9.3

### ISSUE THREAD

**Issue by koppor** [webjars/jshint#17]
According to http://jshint.com/ version 2.9.3 is released.

Minor issue: When pressing `+` at `jshint-node` at http://www.webjars.org/classic, a 404 error is risen.

**Comment by jamesward** [comment]
This will be released shortly.

The issue with the `+` is because `jshint-node` is a submodule of this repo.  And we use the `artifactId` to determine the GitHub repo url.  I've filed an issue for this: https://github.com/webjars/webjars/issues/1481

**Comment by koppor** [comment]
http://www.webjars.org/ still shows 2.9.1, although this repo is updated.

**Comment by jamesward** [comment]
Whoops.  This WebJar requires a manual release step.  I've performed that so the site should be updated in a few hours.
